# For very tiny datasets
# Use if your dataset is < 1000 samples
model_checkpoint: "t5-small"
batch_size: 2
num_train_epochs: 5
learning_rate: 5e-5
weight_decay: 0  # no regularization needed for tiny data
input_max_length: 512
output_max_length: 128
save_steps: 50
eval_steps: 25

