global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "hera-api"
    static_configs:
      - targets: ["hera-api:8000"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
